name: Docker Push TAG

on:
  push:
    tags:
      - v*sha*

jobs:
  docker_tag:
    name: docker_tag
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/*'
    outputs:
      DOCKER_IMAGE_TAGV2: ${{ steps.set-docker-image-tag2.outputs.DOCKER_IMAGE_TAGV2}}
    steps:
      - uses: actions/checkout@v2
      - name: Set Docker Image Tag Based on github tag
        id: set-docker-image-tag2
        run: |
          branch=`git branch --show-current`
          tag=$(echo $branch | tr / _)
          tag=`if [ "$tag" = "develop" ]; then echo "latest-wip"; else echo "$tag"; fi`
          echo "::set-output name=DOCKER_IMAGE_TAGV2::$tag"
      - name: Test
        run: |
          echo $DOCKER_IMAGE_TAGV2
          echo ${{ env.DOCKER_IMAGE_TAGV2 }}
      - name: Create .version file
        run: |
          branch=`git branch --show-current`
          branch=${branch##*/}
          echo $branch+`date '+%Y%m%d'`.sha.`git rev-parse --short HEAD` > .version
          cat .version

  docker_tag2:
    name: docker_tag2
    runs-on: ubuntu-latest
    outputs:
      DOCKER_IMAGE_TAGV3: ${{ steps.set-docker-image-tag3.outputs.DOCKER_IMAGE_TAGV2}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Set Docker Image Tag Based on github tag
        id: set-docker-image-tag3
        run: |
          git tag -l | tail -1
          echo "::set-output name=DOCKER_IMAGE_TAGV2::$(git describe --tags --abbrev=0)"
      - name: Test
        run: |
          echo $DOCKER_IMAGE_TAGV2
          echo ${{ env.DOCKER_IMAGE_TAGV2 }}
      - name: Create .version file
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo $(git describe --tags --abbrev=0) > .version
          cat .version
      - name: Create .version file2
        if: github.ref == 'refs/heads/*'
        run: |
          echo $(git describe --tags --abbrev=0) > .version
          cat .version

  release_docker:
    name: Release_Docker
    needs: docker_tag
    if: github.ref == 'refs/heads/*'
    runs-on: ubuntu-latest
    env:
        DOCKER_IMAGE_TAGV2: ${{ needs.docker_tag.outputs.DOCKER_IMAGE_TAGV2 }}

    steps:
      - name: Build Docker Image Standard
        run: |
          echo "${{ env.DOCKER_IMAGE_TAGV2 }}"

  release_docker2:
    name: Release_Docker2
    needs: docker_tag2
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
        DOCKER_IMAGE_TAGV3: ${{ needs.docker_tag2.outputs.DOCKER_IMAGE_TAGV3 }}
    steps:
      - name: Build Docker Image Standard
        run: |
          echo "${{ env.DOCKER_IMAGE_TAGV3 }}"